<a href="https://colab.research.google.com/github/nhemanth1103/Tensorflow_Learnings/blob/main/tensorflowDL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#What is Tensorflow ?
Tensorflow is an open source machine learning platform developed by google.

**core concept:**It uses data flow graphs for numerical computaion


**DATA FLOW GRAPHS**
A data flow graph is a way of representing computations in terms of a graph where:

 **Nodes** represent operations (e.g., addition, multiplication).

**Edges** represent the data (tensors) that flow between these operations.


TensorFlow 2.x Behavior
In TensorFlow 2.x, eager execution is enabled by default, which means operations are evaluated immediately as they are called from Python. This makes it easier to work with and debug. You can directly print the values of the tensors using .numpy() method to convert them to numpy arrays.


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Define the nodes and operations
x = tf.constant(3.0)
y = tf.constant(2.0)
w = tf.constant(4.0)
add = tf.add(x, y)
multiply = tf.multiply(add, w)

# Create a session to run the graph
with tf.Session() as sess:
    result = sess.run(multiply)
    print(result)

20.0


**Basic Operation in TensorFlow**

**Tensorflow creation**

tf.constant():create constant tensor

tf.variable():create mutable tensors

tf.zeros()tf.ones():create tensor filled with zeros and ones

tf.random.normal():create tensor filled with random values drawn from a normal distrubution

In [ ]:
import tensorflow as tf

#Ensures Tensorflow 2.x behaviour
tf.compat.v1.enable_eager_execution()

#tf.constant():create constant tensors
const_tensor=tf.constant(5.0,dtype=tf.float32)
print("constant Tensor:",const_tensor.numpy())

#tf.variable():create mutable tensors
var_tensor=tf.Variable(5.0,dtype=tf.float32)
print("variable tensor:",var_tensor.numpy())

#tf.zeros(),tf.ones():create tensors fill with zeros and ones
zeros_tensors=tf.zeros([3,3],dtype=tf.float32)
ones_tensors=tf.ones([3,3],dtype=tf.float32)
print("zero tensor:",zeros_tensors.numpy())
print("ones tensor:",ones_tensors.numpy())

#tf.random.normal():create tensor filled eith random values draen from normal distrubution
random_tensor=tf.random.normal([3,3],mean=0.0,stddev=1.0,dtype=tf.float32)
print("Random values tensor:",random_tensor.numpy())

constant Tensor: 5.0
variable tensor: 5.0
zero tensor: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones tensor: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random values tensor: [[-0.17455043 -1.9261193   0.8137546 ]
 [ 0.24261793  0.25358298  0.04479776]
 [-0.50754935  0.67407566  0.14861229]]


**Mathematical operations**

Addition: tf.add() or '+'


Subtraction: tf.subtract() or '-'


Multiplication: tf.multiply() or '*'


Division: tf.divide() or '/'


Matrix multiplication: tf.matmul()

In [ ]:
import tensorflow as tf

#Ensures tensorflow 2.x behaviour
tf.compat.v1.enable_eager_execution()

a=tf.constant([[1,2],[3,4]],dtype=tf.float32)
b=tf.constant([[5,0],[7,8]],dtype=tf.float32)

# a) Addition
add_result_1 = tf.add(a, b)
add_result_2 = a + b  # Alternative way
print("Addition (tf.add):\n", add_result_1.numpy())
print("Addition (+):\n", add_result_2.numpy())

# b) Subtraction
sub_result_1 = tf.subtract(a, b)
sub_result_2 = a - b  # Alternative way
print("Subtraction (tf.subtract):\n", sub_result_1.numpy())
print("Subtraction (-):\n", sub_result_2.numpy())

# c) Multiplication (element-wise)
mul_result_1 = tf.multiply(a, b)
mul_result_2 = a * b  # Alternative way
print("Multiplication (tf.multiply):\n", mul_result_1.numpy())
print("Multiplication (*):\n", mul_result_2.numpy())

# d) Division (element-wise)
div_result_1 = tf.divide(a, b)
div_result_2 = a / b  # Alternative way
print("Division (tf.divide):\n", div_result_1.numpy())
print("Division (/):\n", div_result_2.numpy())

# e) Matrix multiplication
matmul_result = tf.matmul(a, b)
print("Matrix Multiplication (tf.matmul):\n", matmul_result.numpy())


Addition (tf.add):
 [[ 6.  2.]
 [10. 12.]]
Addition (+):
 [[ 6.  2.]
 [10. 12.]]
Subtraction (tf.subtract):
 [[-4.  2.]
 [-4. -4.]]
Subtraction (-):
 [[-4.  2.]
 [-4. -4.]]
Multiplication (tf.multiply):
 [[ 5.  0.]
 [21. 32.]]
Multiplication (*):
 [[ 5.  0.]
 [21. 32.]]
Division (tf.divide):
 [[0.2               inf]
 [0.42857143 0.5       ]]
Division (/):
 [[0.2               inf]
 [0.42857143 0.5       ]]
Matrix Multiplication (tf.matmul):
 [[19. 16.]
 [43. 32.]]


##Tensor Manipulation:

Reshaping: tf.reshape()


Transposing: tf.transpose()


Concatenation: tf.concat()


Slicing: tensor[start:end]


In [ ]:
import tensorflow as tf

#Ensure tensorflow 2.x behaviour
tf.compat.v1.enable_eager_execution()

#Defining a tensor
tensor=tf.constant([[1, 2, 3], [4, 5, 6]],dtype=tf.float32)
print("Origianl Tensor:\n",tensor.numpy())

# a)Reshaping Tensor
reshape_tensor=tf.reshape(tensor,[3,2])
print("Reshaped Temsor:\n",reshape_tensor.numpy())

# b) Transposing: tf.transpose()
transposed_tensor = tf.transpose(tensor)
print("Transposed Tensor:\n", transposed_tensor.numpy())

# c) Concatenation: tf.concat():means merging
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)
concatenated_tensor = tf.concat([tensor_a, tensor_b], axis=0)  # Concatenate along rows
print("Concatenated Tensor along rows:\n", concatenated_tensor.numpy())

concatenated_tensor_1 = tf.concat([tensor_a, tensor_b], axis=1)  # Concatenate along columns
print("Concatenated Tensor along columns:\n", concatenated_tensor_1.numpy())

# d) Slicing: tensor[start:end]
sliced_tensor = tensor[0:1, 1:3]  # Slice second row and second and third columns
print("Sliced Tensor (first row, second and third columns):\n", sliced_tensor.numpy())


Origianl Tensor:
 [[1. 2. 3.]
 [4. 5. 6.]]
Reshaped Temsor:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Transposed Tensor:
 [[1. 4.]
 [2. 5.]
 [3. 6.]]
Concatenated Tensor along rows:
 [[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenated Tensor along columns:
 [[1. 2. 5. 6.]
 [3. 4. 7. 8.]]
Sliced Tensor (first row, second and third columns):
 [[2. 3.]]


##TensorFlow Data Types

a) Numeric Types:
- tf.float32, tf.float64: Floating-point numbers
- tf.int8, tf.int16, tf.int32, tf.int64: Signed integers
- tf.uint8, tf.uint16: Unsigned integers
- tf.bool: Boolean values

b) String Type:
- tf.string: For text data

c) Complex Number Types:
- tf.complex64, tf.complex128: Complex numbers

d) Quantized Types:
- tf.qint8, tf.quint8, tf.qint32: For quantized operations

In [ ]:
import tensorflow as tf


# a) Numeric Types:
# Floating-point numbers
float32_tensor = tf.constant(3.14, dtype=tf.float32)
float64_tensor = tf.constant(3.14, dtype=tf.float64)

# Signed integers
int8_tensor = tf.constant(127, dtype=tf.int8)
int16_tensor = tf.constant(32767, dtype=tf.int16)
int32_tensor = tf.constant(2147483647, dtype=tf.int32)
int64_tensor = tf.constant(9223372036854775807, dtype=tf.int64)

# Unsigned integers
uint8_tensor = tf.constant(255, dtype=tf.uint8)
uint16_tensor = tf.constant(65535, dtype=tf.uint16)

# Boolean
bool_tensor = tf.constant(True, dtype=tf.bool)

# b) String Type:
string_tensor = tf.constant("Hello, TensorFlow!", dtype=tf.string)

# c) Complex Number Types:
complex64_tensor = tf.constant(1 + 2j, dtype=tf.complex64)
complex128_tensor = tf.constant(1 + 2j, dtype=tf.complex128)

# d) Quantized Types:
# These are typically used in specific quantization contexts
qint8_tensor = tf.quantization.quantize(tf.constant([-1.0, 0.0, 1.0]), -1.0, 1.0, tf.qint8)
quint8_tensor = tf.quantization.quantize(tf.constant([0.0, 1.0, 2.0]), 0.0, 2.0, tf.quint8)
qint32_tensor = tf.quantization.quantize(tf.constant([-1.0, 0.0, 1.0]), -1.0, 1.0, tf.qint32)

# Print out the tensors to see their values and types
print("float32:", float32_tensor)
print("float64:", float64_tensor)
print("int8:", int8_tensor)
print("int16:", int16_tensor)
print("int32:", int32_tensor)
print("int64:", int64_tensor)
print("uint8:", uint8_tensor)
print("uint16:", uint16_tensor)
print("bool:", bool_tensor)
print("string:", string_tensor)
print("complex64:", complex64_tensor)
print("complex128:", complex128_tensor)
print("qint8:", qint8_tensor)
print("quint8:", quint8_tensor)
print("qint32:", qint32_tensor)

float32: tf.Tensor(3.14, shape=(), dtype=float32)
float64: tf.Tensor(3.14, shape=(), dtype=float64)
int8: tf.Tensor(127, shape=(), dtype=int8)
int16: tf.Tensor(32767, shape=(), dtype=int16)
int32: tf.Tensor(2147483647, shape=(), dtype=int32)
int64: tf.Tensor(9223372036854775807, shape=(), dtype=int64)
uint8: tf.Tensor(255, shape=(), dtype=uint8)
uint16: tf.Tensor(65535, shape=(), dtype=uint16)
bool: tf.Tensor(True, shape=(), dtype=bool)
string: tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)
complex64: tf.Tensor((1+2j), shape=(), dtype=complex64)
complex128: tf.Tensor((1+2j), shape=(), dtype=complex128)
qint8: QuantizeV2(output=<tf.Tensor: shape=(3,), dtype=qint8, numpy=array([-128,   -1,  127], dtype=int8)>, output_min=<tf.Tensor: shape=(), dtype=float32, numpy=-1.0>, output_max=<tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
quint8: QuantizeV2(output=<tf.Tensor: shape=(3,), dtype=quint8, numpy=array([  0, 128, 255], dtype=uint8)>, output_min=<tf.Tensor: shape=(), dtype=floa

## Defining Operations in TensorFlow

Defining a Simple Function: Use standard Python function definition to create operations. In TensorFlow 2.x, these are executed eagerly by default.


Using tf.function for Performance Optimization:
- Decorate functions with @tf.function to compile them into a static graph for faster execution.
- tf.function improves performance by optimizing and parallelizing the execution of operations.


In [ ]:
import tensorflow as tf

tf.compat.v1.enable_eager_execution()

def simple_operation(a,b):
  return tf.add(a,b)

@tf.function
def optimized_operation(a,b):
  return tf.add(a,b)

a=tf.constant(10)
b=tf.constant(20)

result_simple=simple_operation(a,b)
result_optimized=optimized_operation(a,b)

print("simple operation result:",result_simple.numpy())
print("optimized operation result:",result_optimized.numpy())

simple operation result: 30
optimized operation result: 30


##Layering Nested Operations
Creating Complex Operations by Nesting Functions

In [ ]:
import tensorflow as tf

# Define nested functions
def add_and_multiply(a, b):
    add_result = tf.add(a, b)
    mul_result = tf.multiply(a, b)
    return add_result, mul_result

# Higher-level function that uses the nested function
def complex_operation(x, y, z):
    add_mul_result = add_and_multiply(x, y)
    final_result = tf.subtract(add_mul_result[0], z)
    return final_result

# Sample inputs
x = tf.constant(5)
y = tf.constant(3)
z = tf.constant(2)

# Execute the complex operation
result = complex_operation(x, y, z)
print("Complex Operation Result:", result.numpy())

#5 Practice Problems

1.create a tensor 2*3 floating point number values
[[1.2, 3.4, 5.6], [7.8, 9.0, 1.1]]

In [ ]:
import tensorflow as tf
#creating a tensor
tensor_1=tf.constant([[1.2, 3.4, 5.6], [7.8, 9.0, 1.1]],dtype=tf.float32)
#print the tensor shape and it's type
print("Tensor:\n",tensor_1)
print("Tensor shape:",tensor_1.shape)
print("Tensor type:",tensor_1.dtype)

Tensor:
 tf.Tensor(
[[1.2 3.4 5.6]
 [7.8 9.  1.1]], shape=(2, 3), dtype=float32)
Tensor shape: (2, 3)
Tensor type: <dtype: 'float32'>


Problem 2: Tensor Operations
Create two 3x3 tensors and perform element-wise addition, subtraction, and multiplication.[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]


In [ ]:
import tensorflow as tf
tensor_1=tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]],dtype=tf.int32)
tensor_2=tf.constant([[9, 8, 7], [6, 5, 4], [3, 2, 1]],dtype=tf.int32)
add_tensors=tf.add(tensor_1,tensor_2)
sub_tensor=tf.subtract(tensor_1,tensor_2)
div_tensor=tf.divide(tensor_1,tensor_2)
multiply_tensor=tf.multiply(tensor_1,tensor_2)
print("Additional results:\n",add_tensors)
print("substraction result:\n",sub_tensor)
print("division results\n",div_tensor)
print("multiply results\n",multiply_tensor)

Additional results:
 tf.Tensor(
[[10 10 10]
 [10 10 10]
 [10 10 10]], shape=(3, 3), dtype=int32)
substraction result:
 tf.Tensor(
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]], shape=(3, 3), dtype=int32)
division results
 tf.Tensor(
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]], shape=(3, 3), dtype=float64)
multiply results
 tf.Tensor(
[[ 9 16 21]
 [24 25 24]
 [21 16  9]], shape=(3, 3), dtype=int32)


Problem 3: Reshaping a Tensor
Create a tensor of shape (3, 2) and reshape it into a tensor of shape (2, 3).values[[1, 2], [3, 4], [5, 6]]


In [ ]:
import tensorflow as tf
tensor_a=tf.constant([[1, 2], [3, 4], [5, 6]],dtype=tf.int32)
tensor_b=tf.reshape(tensor_a,[2,3])
print(tensor_b)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


Problem 4: Creating Zeros and Ones Tensors
Create a tensor of all zeros of shape (3, 3) and another tensor of all ones of shape (2, 4).

In [ ]:
import tensorflow as tf
tensor_zeros=tf.zeros([3,3])
tensor_ones=tf.ones({2,4})
print("zeros tensor:\n",tensor_zeros)
print("ones tensor:\n",tensor_ones)

zeros tensor:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
ones tensor:
 tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


Problem 5: Random Tensors
Generate a 4x4 tensor with random values from a normal distribution and a 2x2 tensor with random values from a uniform distribution.....?UNIFORM:Values are equally likely within a given range(minval,maxval).
NORMAL:Values cluster around the mean, following a bell curve(mean,stddev).

In [ ]:
import tensorflow as tf
normal_tensor=tf.random.normal([4,4],mean=0,stddev=1)
uniform_tensor=tf.random.uniform([2,2],minval=0,maxval=1)
print("Normal distrubution tensor:\n",normal_tensor)
print("Uniform distrubution tensor:\n",uniform_tensor)

Normal distrubution tensor:
 tf.Tensor(
[[-1.0432969   0.90708536  0.7989642  -1.0304294 ]
 [-0.08852495 -0.21376167 -0.25020835 -0.57017976]
 [ 0.48617557  1.3563063  -0.8597052  -0.7922548 ]
 [ 1.2525339  -0.39352372 -0.4467469  -0.4530071 ]], shape=(4, 4), dtype=float32)
Uniform distrubution tensor:
 tf.Tensor(
[[0.69784975 0.5108408 ]
 [0.14973617 0.84783447]], shape=(2, 2), dtype=float32)


## Building and Executing Computational Graphs in TensorFlow
TensorFlow allows you to build and execute computational graphs. With TensorFlow 2.x, eager execution is enabled by default, making it easier to develop and debug models. However, you can still build and execute static computational graphs using @tf.function for performance optimization. Here’s a detailed look at both approaches:

1.**Eager Execution (Dynamic Graphs)**

Eager execution allows operations to be executed immediately, providing a more intuitive and interactive way to build and test your models.

In [ ]:
import tensorflow as tf

# Enable eager execution (default in TensorFlow 2.x)
print("Eager execution:", tf.executing_eagerly())

# Define tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Perform operations
c = a + b
d = a * b

# Print results
print("Addition result (eager execution):", c.numpy())
print("Multiplication result (eager execution):", d.numpy())


Eager execution: True
Addition result (eager execution): 5.0
Multiplication result (eager execution): 6.0


2. Static Graphs (Using @tf.function)
Static graphs allow TensorFlow to optimize and parallelize the execution of operations, improving performance for repeated executions.

Example: Static Graph Execution with @tf.function

In [ ]:
import tensorflow as tf

# Define a function using tf.function to create a static graph
@tf.function
def compute_operations(a, b):
    c = tf.add(a, b)
    d = tf.multiply(a, b)
    return c, d

# Define tensors
a = tf.constant(2.0)
b = tf.constant(3.0)

# Execute operations
c, d = compute_operations(a, b)

# Print results
print("Addition result (static graph):", c.numpy())
print("Multiplication result (static graph):", d.numpy())


**Activation functions** are mathematical functions used in neural networks to introduce non-linearity into the model. They are a critical component because they enable neural networks to learn and represent complex patterns. Without activation functions, a neural network would simply be a linear regression model, regardless of the number of layers.


In [ ]:
import tensorflow as tf

# Ensure TensorFlow 2.x behavior
tf.compat.v1.enable_eager_execution()

# Define a sample tensor
tensor = tf.constant([-1.0, 0.0, 1.0], dtype=tf.float32)
print("Original Tensor:\n", tensor.numpy())

# a) ReLU (Rectified Linear Unit): tf.nn.relu()
relu_tensor = tf.nn.relu(tensor)
print("ReLU Applied:\n", relu_tensor.numpy())

# b) Sigmoid: tf.nn.sigmoid()
sigmoid_tensor = tf.nn.sigmoid(tensor)
print("Sigmoid Applied:\n", sigmoid_tensor.numpy())

# c) Tanh (Hyperbolic Tangent): tf.nn.tanh()
tanh_tensor = tf.nn.tanh(tensor)
print("Tanh Applied:\n", tanh_tensor.numpy())


Original Tensor:
 [-1.  0.  1.]
ReLU Applied:
 [0. 0. 1.]
Sigmoid Applied:
 [0.26894143 0.5        0.7310586 ]
Tanh Applied:
 [-0.7615942  0.         0.7615942]


## Building Neural Networks with Multiple Layers


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

#Define a simple neural network
model=models.Sequential([
    layers.Dense(32,activation='relu',input_shape=(64,)),
    layers.Dense(64,activation='relu'),
    layers.Dense(10,activation='softmax')
])

#print the model summary
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,842 (18.91 KB)

 Trainable params: 4,842 (18.91 KB)

 Non-trainable params: 0 (0.00 B)

Explanation:

Sequential API: Use tf.keras.Sequential to stack layers in a linear manner.

Dense Layers: Define fully connected layers with tf.keras.layers.Dense.

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

# Define a more complex model
model = models.Sequential()

# Adding layers incrementally
model.add(layers.Dense(32, activation='relu', input_shape=(64,)))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

# Print the model summary
model.summary()


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,842 (18.91 KB)

 Trainable params: 4,842 (18.91 KB)

 Non-trainable params: 0 (0.00 B)

Explanation:

- Layer Management: Add layers incrementally to a tf.keras.Sequential model.
- Model Summary: Use model.summary() to display the model architecture and parameters.

Key Points:
- Layering Nested Operations: Create complex operations by nesting functions and organizing code for readability and maintainability.
- Working with Multiple Layers: Build neural networks with multiple layers using tf.keras, leveraging the Sequential API to simplify layer management.

## Implementing Loss Functions

Common Loss Functions

MSE(Mean squared error):Measures the average squared difference between the predicted and actual values.

In [ ]:
import tensorflow as tf

#Usage of MSE
y_true=tf.constant([1.0,2.0,3.0])
y_pred=tf.constant([1.1,2.1,2.9])
mse=tf.keras.losses.MeanSquaredError()
loss=mse(y_true,y_pred)
print("MSE loss:",loss.numpy())

MSE loss: 0.009999989


**Categorical Cross-Entropy:**Measues the difference between two probability distrubution for classification tasks.

In [ ]:
import tensorflow as tf

#Usage of categorical cross-Entropy
y_true=tf.constant([[0,1,0],[0,0,1]])
y_pred=tf.constant([[0.05,0.95,0.0],[0.1,0.8,0.1]])
cce=tf.keras.losses.CategoricalCrossentropy()
loss=cce(y_true,y_pred)
print("Categorical cross-Entropy Loss:",loss.numpy())


Categorical cross-Entropy Loss: 1.1769392


**Custom Loss Functions:**Defines a custom loss function by creating a funtion that takes true labels and predictions as input and returns a scalar loss value.

In [ ]:
import tensorflow as tf

# Custom loss function
def custom_loss_function(y_true, y_pred):
    return tf.reduce_mean(tf.abs(y_true - y_pred))

# Example usage of custom loss function
y_true = tf.constant([1.0, 2.0, 3.0])
y_pred = tf.constant([1.1, 2.1, 2.9])
loss = custom_loss_function(y_true, y_pred)
print("Custom Loss:", loss.numpy())


Custom Loss: 0.09999994


#Tensorflow learning algorithms

The algorithms includes such as:
- Linear Regression
- Classification
- Clustering
- Hidden Markov Models

#Linear Regression
